# Generated by Django 4.1 on 2022-09-05 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0007_moviereviews_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата фильма',
                'verbose_name_plural': 'Даты фильмов',
            },
        ),
        migrations.CreateModel(
            name='TimeTableMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_movie', models.DateTimeField(verbose_name='Дата сеанса')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_table', to='movies.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Расписание фильма',
                'verbose_name_plural': 'Расписание фильмов',
            },
        ),
    ]
