# Generated by Django 4.1 on 2022-09-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablemovie',
            name='time_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_table_movie', to='timetable.timetable'),
        ),
    ]
