# Generated by Django 4.1 on 2022-09-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_hall_timetablemovie_hall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
    ]
