# Generated by Django 4.1 on 2022-09-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_hall_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_movie', models.TimeField(verbose_name='Время фильма')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='date_slug',
            field=models.SlugField(default=1, verbose_name='Slug для даты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetablemovie',
            name='time_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_time', to='timetable.timemovie', verbose_name='Время фильма'),
        ),
    ]
