# Generated by Django 4.1 on 2022-09-07 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_timemovie_timetable_date_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timemovie',
            options={'verbose_name': 'Время фильма', 'verbose_name_plural': 'Время фильмов'},
        ),
        migrations.RemoveField(
            model_name='timetablemovie',
            name='time_movie',
        ),
        migrations.AddField(
            model_name='timemovie',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_table_movie', to='timetable.timetablemovie'),
            preserve_default=False,
        ),
    ]
