# Generated by Django 4.1 on 2022-09-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(default=1, verbose_name='Ссылка на трейлер'),
            preserve_default=False,
        ),
    ]
