# Generated by Django 4.1 on 2022-09-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_trailer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie_images/', verbose_name='Скриншоты к фильму')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_post', to='movies.movie', verbose_name='Пост')),
            ],
        ),
    ]
