# Generated by Django 4.1 on 2022-09-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cast_image/', verbose_name='Фотография')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('person', models.CharField(max_length=100, verbose_name='Кем является')),
                ('movie_person', models.CharField(max_length=100, verbose_name='Роль')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cast', to='movies.movie')),
            ],
        ),
    ]
