# Generated by Django 4.1 on 2022-09-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_castmovie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castmovie',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='movieimage',
            options={'verbose_name': 'Фотография к фильму', 'verbose_name_plural': 'Фотографии к фильмам'},
        ),
    ]
