# Generated by Django 4.1 on 2022-09-05 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_moviereviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereviews',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_movie', to='movies.movie', verbose_name='Фильм которому оставляется отзыв'),
            preserve_default=False,
        ),
    ]
