# Generated by Django 4.1.1 on 2023-06-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_moviereviews_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hall',
            field=models.CharField(default=1, max_length=20, verbose_name='Зал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.CharField(default=1, max_length=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.CharField(default=1, max_length=5, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
