# Generated by Django 4.1 on 2022-08-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройка сайта', 'verbose_name_plural': 'Настройки сайтов'},
        ),
    ]
