# Generated by Django 4.1 on 2022-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_settings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advert/', verbose_name='Фотография рекламы')),
                ('url_advert', models.URLField(verbose_name='Ссылка на рекламу')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
    ]
