# Generated by Django 4.1 on 2022-09-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_arvert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arvert',
            new_name='Advert',
        ),
    ]
